package user;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import mysql.MysqlConnection;
import utilities.JLabelImage;
import utilities.ScaleImage;

/**
 *
 * @author gab-uwu
 */
public class UpdateForm extends javax.swing.JFrame {

    /**
     * Creates new form FoodTemplate
     */
    MysqlConnection conexcion = new MysqlConnection();
    Connection conn = conexcion.getConection();
    File file = null;
    int id;

    public UpdateForm(int id) {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.id = id;
        getData(id);
    }

    public UpdateForm() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Body = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        FieldTitle = new javax.swing.JTextField();
        section = new javax.swing.JPanel();
        foodImage = new javax.swing.JLabel();
        Steps = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Ingredients = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FieldIngredients = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        FieldSteps = new javax.swing.JTextArea();
        btnImage = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        FieldDescription = new javax.swing.JTextArea();
        Description = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(230, 230, 230));
        jScrollPane1.setBorder(null);

        Body.setBackground(new java.awt.Color(230, 230, 230));

        Header.setBackground(new java.awt.Color(230, 230, 230));

        btnBack.setBackground(new java.awt.Color(255, 102, 0));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Cancelar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        FieldTitle.setFont(new java.awt.Font("Open Sauce Sans Black", 1, 36)); // NOI18N
        FieldTitle.setForeground(new java.awt.Color(35, 61, 76));
        FieldTitle.setText("Titulo de la receta");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(FieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        section.setBackground(new java.awt.Color(255, 255, 255));

        foodImage.setBackground(new java.awt.Color(254, 127, 46));

        Steps.setFont(new java.awt.Font("Open Sauce Sans", 1, 18)); // NOI18N
        Steps.setForeground(new java.awt.Color(0, 0, 0));
        Steps.setText("Pasos");

        Ingredients.setFont(new java.awt.Font("Open Sauce Sans", 1, 18)); // NOI18N
        Ingredients.setForeground(new java.awt.Color(0, 0, 0));
        Ingredients.setText("Ingredientes");

        FieldIngredients.setBackground(new java.awt.Color(255, 255, 255));
        FieldIngredients.setColumns(20);
        FieldIngredients.setFont(new java.awt.Font("Open Sauce Sans", 0, 14)); // NOI18N
        FieldIngredients.setForeground(new java.awt.Color(51, 51, 51));
        FieldIngredients.setLineWrap(true);
        FieldIngredients.setRows(5);
        FieldIngredients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane2.setViewportView(FieldIngredients);

        FieldSteps.setBackground(new java.awt.Color(255, 255, 255));
        FieldSteps.setColumns(20);
        FieldSteps.setFont(new java.awt.Font("Open Sauce Sans", 0, 14)); // NOI18N
        FieldSteps.setForeground(new java.awt.Color(51, 51, 51));
        FieldSteps.setLineWrap(true);
        FieldSteps.setRows(5);
        FieldSteps.setText("\n");
        FieldSteps.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setViewportView(FieldSteps);

        btnImage.setFont(new java.awt.Font("Open Sauce Sans", 1, 18)); // NOI18N
        btnImage.setText("Subir imagen");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(35, 61, 76));
        btnSave.setFont(new java.awt.Font("Open Sauce Sans", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        FieldDescription.setBackground(new java.awt.Color(255, 255, 255));
        FieldDescription.setColumns(20);
        FieldDescription.setFont(new java.awt.Font("Open Sauce Sans", 0, 14)); // NOI18N
        FieldDescription.setForeground(new java.awt.Color(51, 51, 51));
        FieldDescription.setLineWrap(true);
        FieldDescription.setRows(5);
        FieldDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane4.setViewportView(FieldDescription);

        Description.setFont(new java.awt.Font("Open Sauce Sans", 1, 18)); // NOI18N
        Description.setForeground(new java.awt.Color(0, 0, 0));
        Description.setText("Descripcion");

        javax.swing.GroupLayout sectionLayout = new javax.swing.GroupLayout(section);
        section.setLayout(sectionLayout);
        sectionLayout.setHorizontalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foodImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sectionLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Description)
                        .addComponent(Steps)
                        .addComponent(Ingredients)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane2)
                        .addComponent(btnImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        sectionLayout.setVerticalGroup(
            sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionLayout.createSequentialGroup()
                .addComponent(foodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Ingredients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Steps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(Body);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 550));
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        updateData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Images", "jpg", "png", "jpeg");
        fc.setFileFilter(filtro);

        int selection = fc.showOpenDialog(this);
        if (selection == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
            JLabelImage image = new JLabelImage();
            image.scalelImageExt(path, foodImage);
        }
    }//GEN-LAST:event_btnImageActionPerformed

    public void getData(int id) {
        try {

            PreparedStatement ps;
            ResultSet res;
            ps = conn.prepareStatement("SELECT * FROM Receta WHERE id = " + id);
            res = ps.executeQuery();
            res.next();

            BufferedImage buffimg = null;
            byte[] image = null;
            image = res.getBytes("url_imagen");
            // Lee la imagen como InputStream
            InputStream img = res.getBinaryStream(5);
            buffimg = ImageIO.read(img);
            JLabelImage icon = new JLabelImage();
            icon.scalelImageMysql(buffimg, foodImage);

            FieldTitle.setText(res.getString("nombre"));
            FieldSteps.setText(res.getString("procedimiento"));
            FieldDescription.setText(res.getString("descripcion"));
            FieldIngredients.setText(res.getString("ingredientes"));

        } catch (SQLException ex) {
            System.out.println("muelto");
        } catch (IOException er) {
            Logger.getLogger(FoodTemplate.class.getName()).log(Level.SEVERE, null, er);
        }
    }

    public void updateData() {
        try {
            FileInputStream fis = new FileInputStream(file);
            PreparedStatement ps;
            String query = "UPDATE Receta SET nombre = ?, procedimiento = ?, descripcion = ?, ingredientes = ?, url_imagen = ? WHERE ID = "+id;
            ps = conn.prepareStatement(query);
            ps.setString(1, FieldTitle.getText());
            ps.setString(2, FieldSteps.getText());
            ps.setString(3, FieldDescription.getText());
            ps.setString(4, FieldIngredients.getText());
            ps.setBinaryStream(5, fis, (int) file.length());
            ps.execute();

            JOptionPane.showMessageDialog(null, "Registro actualizado con exito.");

            FoodTemplate view = new FoodTemplate(conn, id);
            Thread hilo = new Thread(view);
            hilo.start();
            try {
                hilo.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
            }
            view.setVisible(true);
            dispose();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No se ha elegido una imagen para la receta");
        } catch (SQLException er) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, er);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel Description;
    private javax.swing.JTextArea FieldDescription;
    private javax.swing.JTextArea FieldIngredients;
    private javax.swing.JTextArea FieldSteps;
    private javax.swing.JTextField FieldTitle;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Ingredients;
    private javax.swing.JLabel Steps;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel foodImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel section;
    // End of variables declaration//GEN-END:variables
}
